name: my-demo-deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    uses: ./.github/workflows/reusable.yml
    with:
      app_name: react-webapp
    secrets:
      deployment_code: zipcode
  print-deployment-result:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: print deployment result
        run: echo ${{needs.deploy.outputs.result}}
