name: my-demo-deployment
on:
  push:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
  deploy:
    needs: [checkout]
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        uses: ./.github/workflows/reusable.yml
