name: Reusable Deploy
on:
  workflow_call:
    inputs:
      app_name:
        default: "web application"
        description: "this is the name of the web application"
        type: string
    secrets:
      deployment_code:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: echo "Deploying...${{inputs.app_name}} with ${{secrets.deployment_code}}"
