name: Reusable workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare and release build
        uses: ./github/workflows/reusable.yml
